#!/bin/ksh

# WORK IN PROGRESS. Not ready for use yet.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#											#
#	Copyright (c) 2022-2023, Ian LeCorbeau <I-LeCorbeau (at) protonmail (dot) com>	#
#											#
#	Permission to use, copy, modify, and/or distribute this software for any	#
#	purpose with or without fee is hereby granted, provided that the above		#
#	copyright notice and this permission notice appear in all copies.		#
#											#
#	THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES	#
#	WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF		#
#	MERCHANTABILITY AND FITNESS IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR		#
#	ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES		#
#	WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN		#
#	ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF		#
#	OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.			#
#											#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

VERSION="01"
DATE=$(date +"%Y%m%d")
REPODIR=$(pwd)
CONFIG="$REPODIR"/iso.conf

# Using the shlib from the iso's config directory to have a self-contained
# build process.
. config/includes.chroot_after_packages/lib/ragnarok-shlib

# TODO: this script is written in ksh (the OpenBSD version). In order to allow
# building the iso from any Debian system with only live-build and its deps
# present, a bash version should be created. This is not a priority, however.
# oksh is easily installable on Debian with either the custom Ragnarok package
# or from upstream at https://github.com/ibara/oksh

usage() {
	printf '%s\n' "
mkiso: script to build the Ragnarok iso.

This script needs to be run from the repo directory, and takes the
following options:

-b	build the iso
-c	clean the repo before or after build
-g	regenerate after modifying config file (see iso.conf)
-h	print help page
-s	sign the iso with signify(1), supplying private key location as arg 1
-u	update iso name (with build date) and syslinux's splash.svg

When multiple options are supplied, they need to be placed in the order in which
each stage is performed, e.g. './mkiso -g -b -s' to generate a new config, build
then sign the iso.

Always run './mkiso -c' before pushing to a repository.
"
}

# This script should never be run as root. However, lb build and lb clean require
# root privileges, so doas is called directly. If doas isn't installed, sudo will
# be called instead.
get_root() {
	if command -v /usr/bin/doas >/dev/null 2>&1; then
		/usr/bin/doas "$@"
	else
		echo "using sudo instead"
		/usr/bin/sudo "$@"
	fi
}

copy_files() {
	# Getting dummy packages
	git -C "$HOME"/.local/src/ clone https://github.com/RagnarokOS/equivs.git
	mkdir -p "$WORKDIR"/config/packages.chroot/ && \
		cp "$HOME"/.local/src/equivs/dummies/*.deb "$WORKDIR"/config/packages.chroot/

}

conf() {
	local _codename _distro _version _flavour _mode _publisher _pretty _bootparams

	_codename=$(getvar CODENAME "$CONFIG")
	_distro=$(getvar DISTRO "$CONFIG")
	_version=$(getvar VERSION "$CONFIG")
	_flavour=$(getvar FLAVOUR "$CONFIG")
	_mode=$(getvar ISOMODE "$CONFIG")
	_publisher=$(getvar PUBLISHER "$CONFIG")
	_pretty=$(getvar PRETTY_NAME "$CONFIG")
	_bootparams=$(getvar BOOTPARAMS "$CONFIG")
	

	echo "Generating config..."
	lb config \
		-d "$_flavour" \
		--debian-installer none \
		--iso-publisher "$_publisher" \
		--initsystem sysvinit \
		--checksums sha512 \
		--image-name "$_distro"-"$_codename"-"$_mode"-"$DATE" \
		--hdd-label "$(echo $_distro | sed 's/.*/\U&/')"_"$(echo $_mode | sed 's/.*/\U&/')" \
		--iso-application "$_pretty" \
		--iso-volume "$_pretty"-"$_version" \
		--archive-areas "main contrib non-free" \
		--debootstrap-options "--variant=minbase" \
		--bootappend-live "$_bootparams"
}

# Generating splash.png for isolinux, based on splash.svg.in
gen_splash() {
	echo "generating splash"

	local _codename _mode _pretty _kernel _publisher _version
	_codename=$(getvar CODENAME "$CONFIG")
	_mode=$(getvar ISOMODE "$CONFIG")
	_publisher=$(getvar PUBLISHER "$CONFIG")
	_pretty=$(getvar PRETTY_NAME "$CONFIG")
	_version=$(getvar VERSION "$CONFIG")
	_kernel=$(uname -r)

	cp config/bootloaders/syslinux_common/splash.svg.in config/bootloaders/syslinux_common/splash.svg

	sed -i	-e "s#@PRETTY@#$_pretty#g" \
		-e "s#@MODE@#$_mode#g" \
		-e "s#@PUBLISHER@#$_publisher#g" \
		-e "s#@DATE@#$DATE#g" \
		-e "s#@VERSION@#$_version#g" \
		-e "s#@CODENAME@#$_codename#g" \
		-e "s#@LINUX_VERSION@#$_kernel#g" \
		config/bootloaders/syslinux_common/splash.svg
}

build() {
	echo "building iso..."

	get_root lb build
}

# Custom packages are temporarily stored in config/packages.chroot and signed with
# Signify. To be extra safe, their signature should be verified before the iso is
# created.
verif_pkgs() {


	local _version _pubkey

	_version=$(getvar VERSION "$CONFIG")
	_pubkey="/etc/signify/ragnarok$_version.pub"
	
	cd "$REPODIR"/config/packages.chroot/ && \
		# If verification fails, the script should stop immediately.
		if ! signify -C -p "$_pubkey" -x SHA256.sig; then
			echo "Bad signature. Exiting..."
			exit 1
		else
			: # keep going
		fi
}

gen_sig() {
	local _seckey _pubkey _isoname
	
	# Full path to .sec and .pub Signify keys.
	# Never share the path to the .sec key.
	_seckey="$1"		# points to $SECKEY, which is this script's first and only argument.
	_pubkey="/etc/signify/ragnarok01.pub"

	_isoname=ragnarok-"$VERSION"-live-"$DATE"-amd64.hybrid.iso

	cd "$WORKDIR" || exit

	# Sign the file
	/usr/bin/signify-openbsd -S -s "$_seckey" -m "$_isoname" -x "$_isoname".sig

	# Verify for good measure
	/usr/bin/signify-openbsd -V -p "$_pubkey" -x "$_isoname".sig -m "$_isoname"
}

# Cleaning up
do_clean() {
	# The bootloader config is regenerated at every build, so we clean up
	# the directory.
	rm config/bootloaders/syslinux_common/splash.svg
	#get_root lb clean
}

# If the iso config ever has to be restarted from scratch
do_gen() {
	#conf
	gen_splash
}

do_build() {
	copy_files
	gen_splash
	build
}

# Before rebuilding the iso
do_update() {
	lb config "$DATE"
	gen_splash
}

SECKEY=
while getopts bcghus: args; do
	case "$args" in
		b)	do_build ;;
		c)	do_clean ;;
		g)	do_gen ;;
		h)	usage ;;
		u)	do_update ;;
		s)	SECKEY="$OPTARG"
		       	gen_sig "$SECKEY" ;;
		*) usage ;;
	esac
done
shift $((OPTIND-1))
