#!/bin/sh

# $Ragnarok: mktar,v 1.2 2025/05/26 16:05:06 lecorbeau Exp $
# Create a tarball of dir $1.

_dir=$1
_workdir=$(pwd)

_version=$(getval VERSION config.mk)
_name="${_dir}${_version}.tgz"

cd "$_dir" || exit

/usr/bin/tar cpPvf "${_name}" --ingore-failed-read \
	--xattrs-include='*.*' --numeric-owner -X "${_workdir}/excludes.txt" .

cd "$_workdir" || exit
