#!/usr/bin/env perl

# $Ragnarok: runhooks,v 1.1 2025/05/14 23:38:01 lecorbeau Exp $
# Execute hooks in dir $1.

use strict;
use warnings;

my $dir = $ARGV[0];

opendir(my $hookdir, $dir) or die("Cannot open $dir\n");
my @scripts = readdir($hookdir);
closedir($hookdir) or die("Cannot close $dir\n");

@scripts = sort { $a cmp $b } @scripts;

foreach my $script (@scripts) {
	if($script =~ /^\./ or -d "$dir/$script") {
		next;
	}
	if(-x "$dir/$script") {
		print("Running $script from $dir...\n");
		system("$script") == 0
			or die("Cannot run $script, exiting...\n");
	}
}
