# Makefile to build dwm/rt/dmenu all at once.
MAKE	= make -C

all:
	$(MAKE) dwm
	$(MAKE) rt
	$(MAKE) dmenu

install:
	$(MAKE) dwm install
	$(MAKE) rt install
	$(MAKE) dmenu install

clean:
	$(MAKE) dwm clean
	$(MAKE) rt clean
	$(MAKE) dmenu clean

