#!/bin/sh

# $Ragnarok: chrootcmd,v 1.2 2025/07/18 17:22:15 lecorbeau Exp $
# Wrapper script around the chroot command. Can be used by hook scripts
# instead of constantly writing the full thing.

TARGET="$1"
shift
CMD="$*"

/usr/bin/chroot "${TARGET}" /bin/bash -c "source /etc/profile && ${CMD}"
