#!/bin/ksh

# $Ragnarok: cleanup,v 1.2 2023/10/07 18:21:00 lecorbeau Exp $
#
# Clean up the chroot before running tar.

set -e

_TARGET=$1

chroot "$_TARGET" -c /bin/ksh "apt clean && \
	rm -rf /var/lib/apt/lists/*
	rm -rf /var/log/apt/{eipp.log.xz,history.log,term.log}
	rm -rf /var/log/{alternatives.log,dpkg.log}
	rm -rf /var/lib/dbus/machine-id
	rm -rf /etc/{hostname,machine-id,resolv.conf}
	rm -rf /tmp/*"
