#!/bin/ksh

# $Ragnarok: mkrepo,v 1.3 2023/10/08 15:54:59 lecorbeau Exp $
#
# Use reprepro to create a local apt repository containing all the minbase
# packages needed for debootstrap. This not only saves lots of time when
# building the sets, but also solves the *potential* security risks caused
# by debootstrap not being able to fetch from all standard repos at once 
# (e.g. bookworm, bookworm-updates & bookwork-security).

# Name of current Debian stable release
CODENAME="bookworm"

# Download the packages
get_pkgs() {
	mkdir -p ../pkgs
	cp dummies/* ../pkgs
	# remove Ragnarok's dummy base-files package, it'll be installed later.
	rm ../pkgs/base-files_99+ragnarok01_amd64.deb
	cd ../pkgs || exit
	apt-get update
	xargs apt-get download <../iso/pkgs.list
}

# Create the repository
create_repo() {
	local _repo

	_repo="/usr/src/ragnarok/repo"
	mkdir -p "${_repo}/conf"
	touch "${_repo}/conf/distributions"
	printf '%s\n' "Label: local apt repo
Codename: $CODENAME
Architectures: amd64
Components: main
Description: Build-time repo for Ragnarok sets" > "${_repo}/conf/distributions"

	for _deb in /usr/src/ragnarok/pkgs/*.deb; do
		reprepro -Vb "$_repo" includedeb "$CODENAME" "$_deb"
	done
}

get_pkgs
create_repo
