#!/bin/sh

# $Ragnarok: mktar,v 1.4 2025/07/30 19:37:18 lecorbeau Exp $
# Create a tarball of dir $1.

_dir=$1
_workdir=$(pwd)

_version=$(getval VERSION config.mk)
_name="${_dir}${_version}.tar.xz"

cd "$_dir" || exit

/usr/bin/tar cpPJvf "${_workdir}/${_name}" --ingore-failed-read \
	--xattrs-include='*.*' --numeric-owner -X "${_workdir}/excludes.txt" .

cd "$_workdir" || exit
