#!/usr/bin/env perl

# $Ragnarok: runhooks,v 1.2 2025/05/15 15:57:26 lecorbeau Exp $
# Execute hooks in dir $1.

use strict;
use warnings;

my $dir = $ARGV[0];
my $stage = $ARGV[1];

opendir(my $hookdir, $dir) or die("Cannot open $dir\n");
my @files = readdir($hookdir);
closedir($hookdir) or die("Cannot close $dir\n");

@files = sort { $a cmp $b } @files;
my @scripts = grep(/$stage/, @files);

foreach my $script (@scripts) {
	if($script =~ /^\./ or -d "$dir/$script") {
		next;
	}
	if(-x "$dir/$script") {
		print("Running $script from $dir...\n");
		system("$script") == 0
			or die("Cannot run $script, exiting...\n");
	}
}
